#!/bin/sh
#
#(make sure the right shell will be used)
#$ -S /bin/sh
#
#(the cpu time for this job)
#$ -l h_cpu=0:25:00
#
#(the maximum memory usage of this job)
#$ -l h_vmem=1500M
#
#(use hh site)
#$ -l site=hh
#(stderr and stdout are merged together to stdout)
#$ -j y
#
# use SL5
#$ -l os=sld6
#
# use current dir and current environment
#$ -cwd
#$ -V
#
#Used to set the env and go to working dir
#Replace with own pathes
cd /afs/desy.de/user/b/bukinkir/CMSSW_10_2_14/src; 
eval `scramv1 runtime -sh` ;
cd /afs/desy.de/user/b/bukinkir/GeomTauId
